### ISSUE TITLE
Error when opening Guild Tab

### ISSUE THREAD

**Issue by merlinmage** [siweia/NDuiClassic#102]
Message: [ADDON_ACTION_FORBIDDEN] AddOn 'NDui' tried to call the protected function 'GuildControlSetRank()'.
Time: Sat Mar 12 14:40:22 2022
Count: 1
Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'NDui' tried to call the protected function 'GuildControlSetRank()'.
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:2531: in function `GuildControlPopupFrame_Initialize'
[string "@Interface_TBC\FrameXML\FriendsFrame.lua"]:978: in function `FriendsFrame_OnEvent'
[string "*:OnEvent"]:1: in function <[string "*:OnEvent"]:1>

Locals: <none>

**Comment by siweia** [comment]
Make sure this occurs with NDui enabled only.
