### ISSUE TITLE
限时类的任务有一个计时器 (QuestTimerFrame)，能不能美化一下

### ISSUE THREAD

**Issue by Solor** [siweia/NDuiClassic#14]
能不能像 QuakeTimer 一样直接来个进度条放在屏幕中间 ❓ 

![20190914194214](https://user-images.githubusercontent.com/156806/64906305-2e7b3180-d728-11e9-91cd-9a4aa8ce4197.png)

**Comment by siweia** [comment]
https://github.com/siweia/NDuiClassic/commit/19938821c553f9da4ff3be5b2ea4f6736185fbe3
