### ISSUE TITLE
QuestFrameDetailPanel 背景材质

### ISSUE THREAD

**Issue by Solor** [siweia/NDuiClassic#15]
QuestFrameDetailPanel 有一些悬赏任务会有背景材质，黄色的白色的都有，能不能一起清除了

![TIM图片20190916212229](https://user-images.githubusercontent.com/156806/64954264-63be8580-d8c8-11e9-9eff-2a1438fd1db3.png)

![22222](https://user-images.githubusercontent.com/156806/64954873-20fdad00-d8ca-11e9-831f-0fe397593d6f.png)

**Comment by siweia** [comment]
首先我只有3级的号
其次，没有任何人提过这个问题，所以我不觉得这个问题存在。
