### ISSUE TITLE
如何更改不以K 显示血量和能量

### ISSUE THREAD

**Issue by ah-kevin** [siweia/NDuiClassic#16]
能否提供开关,或者代码在哪个文件里面~~写写

**Comment by siweia** [comment]
控制台里找找

**Comment by ah-kevin** [comment]
控制台里面没有这个设置的选项啊-- 
如果还不如直接代码里 把计算改了

**Comment by ah-kevin** [comment]
代码里面 找到了!希望还是后续可以加个开关~ lua 没用过.不然我加了 怀旧服毕竟没有过W的血量- - 看见K强迫症- -
