### ISSUE TITLE
as a player, i want bag resort automatically so that i can find item quickly.

### ISSUE THREAD

**Issue by qiyuqi** [siweia/NDuiClassic#2]
**requirement:**
as a player, i want bag resort function so that i can find item quickly.
作为一个玩家，我希望增加背包整理功能，这样可以方便查到想找的物品

**user story:**
1. open bagnon
2. click resort button on frame bar as usual
3. resort items
4. done

**critical:**
1. asc or desc sort by move frequently low to high and item rare level

**Comment by siweia** [comment]
Fixed in 57c2ac5d63985306194034d6f0b9965208af15c9
