### ISSUE TITLE
Option to scale name plates further away for people with render issues or scale down minions

### ISSUE THREAD

**Issue by vrukkus** [siweia/NDuiClassic#20]
It would be nice to have the sleek nameplates able to be read at a certain distance do to some graphical blurryness to the natty nameplates, and also maybe shrink down or disable pets nameplates, it would be nice to scale this from the console

**Comment by siweia** [comment]
You can scale the nameplates you aren't targetting through console.
Pet nameplates you can disable through the interface option panel that blizzard gives you.
