### ISSUE TITLE
a suggestion

### ISSUE THREAD

**Issue by JisonLove** [siweia/NDuiClassic#21]
First of all, this UI plugin is the best and most useful one I have ever used, very good!

However, during use, it was found that the functions in the plug-in are not complete.
Urgently needed: task assistant, auction house assistant, dungeon drop information, dungeon map and boss position, talent simulator, damage statistics, and more. I use them in combination with other plugins, but the results are not satisfactory.
So I hope that the author can consider integrating some of the more demanding features of the player into the NDUI.

Second.
Some features are not available in the settings panel.
E.g,
The equipment level of the equipment bar is displayed.
Equipment automatic comparison.
The maximum distance setting of the camera.
UI transparency.
The size of the chat window font.
And some of the more useful features I don't know.

Also.
The talent page can't always be displayed, can you make a new page instead of that page. The new page is able to display the talent tree of the three branches. You can see it at a glance.

End: I hope the author can see and seriously consider whether my suggestion is feasible. Thank you!
Remarks: The above text is from Google Translate

**Comment by siweia** [comment]
1. All the features you described can be achieved by a lot of addons already. NDui is not an addon pack to combine all addons together.
2. Most of your issues can be solved via FAQ, and the chat font size can be changed by clicking each header of chat windows. You need to be familier with default functions that Blizz gives you first.
3. This is not necessary, I only write functions that I would be happy with.
