### ISSUE TITLE
How to cancel AuroraClassic Global Font Outline?

### ISSUE THREAD

**Issue by VanDeAnna** [siweia/NDuiClassic#23]
I commented some lines in GUI.lua such as
["Replace default game fonts"] = "Global Font Outline"
and
local fontBox = createToggleBox(gui, "reskinFont", L["Replace default game fonts"], appearance, 7) local fontSlider = CreateFrame("Slider", "AuroraOptionsfontSlider", gui, "OptionsSliderTemplate") fontSlider:SetPoint("TOPLEFT", fontBox, "BOTTOMLEFT", 20, -30) fontSlider:SetMinMaxValues(.5, 1) fontSlider:SetValueStep(0.1) AuroraOptionsfontSliderText:SetText(L["FontScale"]) AuroraOptionsfontSliderLow:SetText(.5) AuroraOptionsfontSliderHigh:SetText(1) local fontValue = fontSlider:CreateFontString(nil, "ARTWORK", "GameFontHighlight") fontValue:SetPoint("TOP", fontSlider, "BOTTOM", 0, 4)

but it seems not working.
The global font outline is way a bit heavy to me.
Is there any way to reduce or cancel it?

**Comment by siweia** [comment]
Why don't you disable it through interface panel?
Or slash cmd /ac

**Comment by VanDeAnna** [comment]
Thanks alot!
