### ISSUE TITLE
破羊提醒

### ISSUE THREAD

**Issue by peifeiyang** [siweia/NDuiClassic#26]
s大，下午好，
我想求个插件实现以下功能（怀旧服）：
我羊了个怪，被队友破羊了。然后聊天就会有“xxxx破羊,技能xxxxx”
找了好久，跪谢了。

**Comment by peifeiyang** [comment]
s大  不给说嘛？

**Comment by peifeiyang** [comment]
这个功能NDui不是有的吗？组队的时候见过一个盗贼朋友使用过，我就想知道这个是s大自己做到NDui里面了，还是个单体的插件。

**Comment by siweia** [comment]
傻子么？控制台自己不会去看一看吗

**Comment by peifeiyang** [comment]
好声好气问你，上来就满嘴芬芳？好好，怪我多嘴，真是无语

**Comment by siweia** [comment]
给你的功能不去了解，看到别人有通报不去问别人用的什么插件，你是来搞笑的吗？
帖子里伸手就算了，还跑这里提issue这是issue吗？对你这种无脑伸手才是无语。

**Comment by peifeiyang** [comment]
我问了，要不然怎么找到这里的？我在nga上提问你不回啊，无脑伸手？我只是想问下这个功能是否是集成在NDui里了还是独立的插件，要是独立的插件我可以单独导入，要是您自己写的我就继续请教。这个确实不是issue，但是在nga上发过，也发过私信。您时间忙没时间看，所以这里也就提了。既然您不愿意赐教也没办法了。

**Comment by siweia** [comment]
你确定帖子没回？？？
我的插件里有这种破控通报功能，但是默认关闭，也从来不是你要的那种通报格式，你想要的压根就不是我插件里的。
“我想求个插件实现以下功能”这是你的原话，这不是伸手吗？
但凡一个看过帖子faq的，都不会无脑问出这种问题。
