### ISSUE TITLE
LibHealComm Error

### ISSUE THREAD

**Issue by archvennom** [siweia/NDuiClassic#27]
Love the UI, as I'm always updating it but today with the new update getting this error message each time I heal.

Message: ...AddOns\NDui\Libs\LibHealComm-4.0\LibHealComm-4.0-71.lua:1422: attempt to index field '?' (a nil value)
Time: Tue Nov 12 16:15:07 2019
Count: 6
Stack: ...AddOns\NDui\Libs\LibHealComm-4.0\LibHealComm-4.0-71.lua:1422: attempt to index field '?' (a nil value)

Locals:

**Comment by siweia** [comment]
Try 1.11.5.

**Comment by archvennom** [comment]
No issues on the update so far :)
