### ISSUE TITLE
战斗中团队小队人物无法调整

### ISSUE THREAD

**Issue by kevin7518** [siweia/NDuiClassic#38]
在战斗中时，无法调整团队里面人物的位置，除非自己死亡后调整，不知道是不是个bug，有些人是可以调整的，我和几个朋友使用nDui都没办法调队伍。

**Comment by siweia** [comment]
你下次试试把全部插件都关了，一个都不开，看看能不能战斗中调整

**Comment by kevin7518** [comment]
今天打团队本试了一下，还是不行，在战斗中还是调不了，我只把ndui插件关了，用默认的就可以调整。

**Comment by kevin7518** [comment]
找了一个人，两个个人开团，进战斗就能调，但是在MC黑龙BWL，30人时候，我都试了，都调不了。关了ndui 重载之后就可以了

**Comment by siweia** [comment]
https://github.com/siweia/NDuiClassic/blob/master/Interface/AddOns/NDui/Core/Database.lua#L20
你按照这里，把20到23行删了试一试。

**Comment by kevin7518** [comment]
今天团队本试过了，战斗中可以调整队伍了，跟这个萨满职业颜色修改有关系么？

**Comment by siweia** [comment]
那应该就是了，改了萨满职业颜色，就会导致这个问题。
