### ISSUE TITLE
Performance issues in 40-man raids

### ISSUE THREAD

**Issue by yFkC1gTR59txdch2dGWT** [siweia/NDuiClassic#40]
Hello
I've been having some performance issues in raids and it seems NDui is the main cause of it
But i'm struggling to pinpoint what I can do to improve to prevent it happening

In smaller groups I have no trouble maintaining 110 FPS (which is the FPS cap I have configured), but in a full raid it starts to drop down below 50 on some fights, this was not a problem I had before with different UIs of similar type (ouf based) with the same combination of other addons
While running a MC raid with around 30 the problem was a lot less pronounced which leads me to think it might be aura on raid frames or similar related
Running the cpu profiler on a fight it measured a peak of 44ms per frame just from NDui
Here is a picture from Firemaw (the peaks are when i'm actually hitting the boss):
![image](https://user-images.githubusercontent.com/25079429/76562418-a2af4b80-64a5-11ea-9dba-275a4b1f3e83.png)
Showing peak on same fight:
![image](https://user-images.githubusercontent.com/25079429/76562510-d1c5bd00-64a5-11ea-9e71-f37adca0e349.png)

Things I've disabled and/or tested:
* Disabled "show unit targeted by" in tooltips: this did not have any meaningful effect
* Disabled aurawatch: this seems to have helped ever so slightly
* Switched to simple raid frames: this seems to have helped a bit more
* Disabled Ufsimplecombattext: this had the biggest impact on the things I've tested (or at least "felt" like it)
All these things combined did not solve the issue, but it helped a bit at the worst times (instead of dipping down to 40-50 at some moments it dipped down to 50-60, but hard to know for sure since I can't recreate the same scenario for testing every time)

Any tips or ideas what the problem can be and what I can do to solve it?

**Comment by siweia** [comment]
Try to disable raidframes, and see how it goes by default UI's raidframes.

**Comment by siweia** [comment]
https://github.com/siweia/NDuiClassic/blob/master/Interface/AddOns/NDui/Modules/UFs/Spawns.lua#L101

And try to delete the line above, the threat indicator may impact on this as well.

What happen if you disable NDui completely?

**Comment by yFkC1gTR59txdch2dGWT** [comment]
I haven't tried disabling NDui completely, but I've gone through a few others ouf based UIs lately where I did not have the problem (with the same combination of other external addons)
but for sanity's sake I'll add this to the list of things to try

In the next raid which sadly won't be until Wednesday I'll do the following:
I'll try disabling the threat indicator first and note the impact, if this doesn't solve the issue I'll move forward with disabling the raid frames all together and see how that goes
and at last if neither of the first two things helped I'll double check with disabling NDui altogether 

I'll report back once I have the results

**Comment by siweia** [comment]
Thx.😬
