### ISSUE TITLE
你好，我有来麻烦你了

### ISSUE THREAD

**Issue by nanjuekaien1** [siweia/NDuiClassic#44]
在其他网站发现个插件，鼠标提示的里面带显示目标天赋功能，代码如下：
local C_PREFIX = "BISTIP1"
local talents = {}

local talentTrees = {
    ["DRUID"] = { [1] = "Balance", [2] = "Feral", [3] = "Restoration" },
    ["HUNTER"] = { [1] = "Beast Mastery", [2] = "Marksmanship", [3] = "Survival" },
    ["MAGE"] = { [1] = "Arcane", [2] = "Fire", [3] = "Frost" },
    ["PALADIN"] = { [1] = "Holy", [2] = "Protection", [3] = "Retribution" },
    ["PRIEST"] = { [1] = "Discipline", [2] = "Holy", [3] = "Shadow" },
    ["ROGUE"] = { [1] = "Assassination", [2] = "Combat", [3] = "Subtlety" },
    ["SHAMAN"] = { [1] = "Elemental", [2] = "Enhancement", [3] = "Restoration" },
    ["WARLOCK"] = { [1] = "Affliction", [2] = "Demonology", [3] = "Destruction" },
    ["WARRIOR"] = { [1] = "Arms", [2] = "Fury", [3] = "Protection" }
}

local inGrp = function()
    return IsInRaid() or IsInGroup(LE_PARTY_CATEGORY_HOME)
end

GameTooltip:HookScript("OnTooltipSetUnit", function(self)
    local _, unit = self:GetUnit()

    if (not unit or not UnitIsPlayer(unit)) then
        return
    end

    local text1 = GameTooltipTextLeft1:GetText()
    if(not text1 or text1 == "") then
        return
    end

    local text2 = GameTooltipTextLeft2:GetText()
    if(not text2 or text2 == "") then
        return
    end

    local localizedClass, class = UnitClass(unit)
    if (localizedClass and class) then
        local classc = (CUSTOM_CLASS_COLORS or RAID_CLASS_COLORS)[class]

        --GameTooltipTextLeft1:SetTextColor(classc.r, classc.g, classc.b)
        text1 = string.format("|c%s%s|r", classc.colorStr, text1)
        text2 = string.gsub(text2, localizedClass, string.format("|c%s%s|r", classc.colorStr, localizedClass), 1)
    end

    local guildName, guildRankName = GetGuildInfo(unit);
    if (guildName and guildRankName) then    
        text2 = string.format("|cFF40FB40%s of <%s>|r\n%s", guildRankName, guildName, text2)
    end

    GameTooltipTextLeft1:SetText(text1)
    GameTooltipTextLeft2:SetText(text2)

    local name = UnitName(unit)
    if (name and class and talents[name]) then
        local spec = 1
        local t1 = talents[name][1]
        local t2 = talents[name][2]
        local t3 = talents[name][3]
        if(t2 > t1) then 
            if (t3 > t2) then
                spec = 3
            else
                spec = 2
            end
        elseif(t3 > t1) then 
            spec = 3
        end
        GameTooltip:AddLine(string.format("Talents:|cFFFFFFFF %s [%d/%d/%d]", talentTrees[class][spec], talents[name][1], talents[name][2], talents[name][3]))
    end
end)

local function sendTalents()
    if (not inGrp()) then 
        talents = {}
        return 
    end

    local t1 = select(3, GetTalentTabInfo(1))
    local t2 = select(3, GetTalentTabInfo(2))
    local t3 = select(3, GetTalentTabInfo(3))
    local msg = t1.."-"..t2.."-"..t3

    C_ChatInfo.SendAddonMessage(C_PREFIX, msg, "RAID")
end

local function receiveTalents(...)
    local prefix, text, _, _, sender = ...

    if(prefix ~= C_PREFIX) then return end

    local t1, t2, t3 = strsplit("-", text)

    t1 = tonumber(t1)
    t2 = tonumber(t2)
    t3 = tonumber(t3)

    if(t1 and t2 and t3) then
        talents[sender] = {}
        talents[sender][1] = t1
        talents[sender][2] = t2
        talents[sender][3] = t3
    end
end

local function onEvent(frame, event, ...)
    if (event == "CHAT_MSG_ADDON") then
        receiveTalents(...)
    else
        sendTalents()
    end
end

local f = CreateFrame("Frame", nil, UIParent)
f:RegisterEvent("CHAT_MSG_ADDON")
f:RegisterEvent("PLAYER_ALIVE")
f:RegisterEvent("CHARACTER_POINTS_CHANGED")
f:RegisterEvent("GROUP_ROSTER_UPDATE")
f:RegisterEvent("PLAYER_ENTERING_WORLD")
f:SetScript("OnEvent", onEvent)
C_ChatInfo.RegisterAddonMessagePrefix(C_PREFIX)

**Comment by siweia** [comment]
没用，别人也要装你才能看得到

**Comment by nanjuekaien1** [comment]
发现这个问题了，谢谢，这次更新打开拍卖行和拾取的时候报错，我发在NGA的帖子里了
