### ISSUE TITLE
自动设置UI缩放在不同分辨率下不能很好的进行缩放

### ISSUE THREAD

**Issue by lrxxs** [siweia/NDuiClassic#47]
如题，

大部分模块位置都能很好得自动缩放，并且位置也没什么问题，

而【头像】模块和【目标】模块需要手动调整坐标。

同样，在技能监控中，【冷却计时】和【自定义监控】，在不同分辨率下也需要手动调整坐标，而不进行自动位移。

以上问题出现在高分辨率（1080P）切换到低分辨率（1440*900）的过程中，没有测试1080P切换到2K分辨率条件。

以上问题仅存在于1.19版本之后。

盼复。

**Comment by siweia** [comment]
测试了并没有任何问题
