### ISSUE TITLE
更新最新版的插件后 BindPad 问题

### ISSUE THREAD

**Issue by kevin7518** [siweia/NDuiClassic#48]
1, 无法修改创建宏的名称了，点击改变名称/图标 就立即消失
2, 技能/宏  原来图标右上角会显示快捷键现在没有了，图标上的文字过大。

**Comment by nanjuekaien1** [comment]
@kevin7518  我 刚才试验了下，最新版本我可以创建宏，点击也没事。2、我=快捷键我的也显示啊

**Comment by kevin7518** [comment]
BindPad 是这个插件吗？

**Comment by kevin7518** [comment]
只开 ndui 和 BindPad 试的，不好使，关闭nDui，只开BindPad  就可以了

**Comment by nanjuekaien1** [comment]
@kevin7518 我没用过  BindPad 插件
