### ISSUE TITLE
Ability to move quest tracker

### ISSUE THREAD

**Issue by VirtualBoost** [siweia/NDuiClassic#5]
I can't seem to find any setting to make the quest tracker movable. Is that possible to fix?

![QuestTrackerMove](https://user-images.githubusercontent.com/17124561/64123255-26c0a200-cda4-11e9-850e-7ab64b66b67c.png)

**Comment by siweia** [comment]
Every time you log in game, the addon would tell you use cmd /ndui for help.
Haven't you ever seen?

**Comment by VirtualBoost** [comment]
I feel incredibly stupid now. Must have missed it completely, thanks for pointing it out!
