### ISSUE TITLE
Ability to flip target 3D portrait

### ISSUE THREAD

**Issue by VirtualBoost** [siweia/NDuiClassic#6]
A cool (and perhaps unnecessary) feature would be the ability to flip the portrait of the target frame, so that the player portrait and the target portrait looks at each other, as some other UIs have. Would that be possible to implement?

Love the UI so far!

![FlipTarget3DPortrait](https://user-images.githubusercontent.com/17124561/64123398-8919a280-cda4-11e9-83a0-8032ca9dc366.png)

**Comment by siweia** [comment]
I'll see what I can do. Good point anyway.

**Comment by VirtualBoost** [comment]
> 
> 
> I'll see what I can do. Good point anyway.

Awesome! If it is to any help, I noticed that some NPCs, such as wolves and spiders, are looking in the "right" direction, i.e. looking towards the player portrait. I'm not entirely sure if that goes for all wolves and spiders of course..

**Comment by siweia** [comment]
You can control model's "looking direction".
If I simply rotate the model, some NPCs might look at the back.
I have to give up on this.
