### ISSUE TITLE
申请增加功能

### ISSUE THREAD

**Issue by nanjuekaien1** [siweia/NDuiClassic#64]
是否可以增加个死亡通报功能，XX死亡，原因：受到XX技能伤害。

**Comment by siweia** [comment]
没必要。Details自带这个功能，你把它开起来就行。skada没用过，应该也有

**Comment by nanjuekaien1** [comment]
我试试去正好装的Details，
下次更新加进去吧，遗漏2个DEBUFF
废墟的[22997] = 2,	-- 瘟疫
神殿的[25991] = 2,	-- 剑毒之雨（维希度斯）

**Comment by nanjuekaien1** [comment]
@siweia Details开了死亡通报，实际没用是个摆设。。。。还要继续去找，现在地雷太多了
