### ISSUE TITLE
NDui Classic - Raid Frame Enquiry

### ISSUE THREAD

**Issue by sscl500** [siweia/NDuiClassic#66]
Hello siweia,

I recently came across your ui and I have two questions with raid frame.

1) I am trying to show totem buffs on raid frame but I am having no luck. I tried adding spell id and aura id but still no luck. Can you please tell me how I could add totem buffs on the raid frame so that I can keep track of who is receiving the buff?

2) I am very used to Healcomm Classic, which keeps track of my heal prediction and other players incoming heal so that I could keep track of who to heal first. Is it possible to show this on raid frame? It helps alot of heal players when it shows my predicted heal and other player's incoming heal.

Thank you!! 👍

**Comment by siweia** [comment]
1. I don't play classic that much, the auras on raidframe only track the actual auras from your buff frame. If the totem doesn't give you buffs on buffframe, there is no way to track that.
2. Haven't you ever seen any incoming heal from others? Because ndui already supports the things you mentioned. You don't need to install any other addons.

**Comment by sscl500** [comment]
Thanks for the replay.
Can you change the colour of the incoming heal from others? Because it overlaps with my heal, which makes it difficult to predict.

**Comment by sscl500** [comment]
> Thanks for the reply.
> Can you change the colour of the incoming heal from others? Because it overlaps with my heal, which makes it difficult to predict.



> 1. I don't play classic that much, the auras on raidframe only track the actual auras from your buff frame. If the totem doesn't give you buffs on buffframe, there is no way to track that.
> 2. Haven't you ever seen any incoming heal from others? Because ndui already supports the things you mentioned. You don't need to install any other addons.

Thanks for the reply.
Can you change the colour of the incoming heal from others? Because it overlaps with my heal, which makes it difficult to predict.
