### ISSUE TITLE
团队框体外观建议

### ISSUE THREAD

**Issue by kevin7518** [siweia/NDuiClassic#67]
可不可以让团队框体的宽度范围设置更小，小于60，增加一个隐藏团队框体玩家姓名的开关，这样可以给一些不用太关注团队的DPS职业，调整成类似Grid那个样子的框架，看上去很简洁

**Comment by nanjuekaien1** [comment]
@kevin7518  有简易模式啊

**Comment by siweia** [comment]
不考虑

**Comment by kevin7518** [comment]
哦，主要是调的很窄名字 会超出框体，没有办法不显示名字
