### ISSUE TITLE
8 LUA Issues after update

### ISSUE THREAD

**Issue by Zabbel** [siweia/NDuiClassic#69]
Hi!
After updating to Version 1.24.0 i've got the follwing issues:

..AddOns\NDui\Modules\ActionBar\Bars\Bar1.lua:4: attempt to index field 'bars' (a nil value)
Count: 1
Call Stack:
[C]: ?
..AddOns\NDui\Modules\ActionBar\Bars\Bar1.lua:4: in main chunk

..AddOns\NDui\Modules\ActionBar\Bars\Bar2.lua:4: attempt to index field 'bars' (a nil value)
Count: 1

Call Stack:
[C]: ?
..AddOns\NDui\Modules\ActionBar\Bars\Bar2.lua:4: in main chunk

..AddOns\NDui\Modules\ActionBar\Bars\Bar3.lua:4: attempt to index field 'bars' (a nil value)
Count: 1

Call Stack:
[C]: ?
..AddOns\NDui\Modules\ActionBar\Bars\Bar3.lua:4: in main chunk

..AddOns\NDui\Modules\ActionBar\Bars\Bar4.lua:4: attempt to index field 'bars' (a nil value)
Count: 1

Call Stack:
[C]: ?
..AddOns\NDui\Modules\ActionBar\Bars\Bar4.lua:4: in main chunk

..AddOns\NDui\Modules\ActionBar\Bars\Bar5.lua:4: attempt to index field 'bars' (a nil value)
Count: 1

Call Stack:
[C]: ?
..AddOns\NDui\Modules\ActionBar\Bars\Bar5.lua:4: in main chunk

...ace\AddOns\NDui\Modules\ActionBar\Bars\Stancebar.lua:4: attempt to index field 'bars' (a nil value)
Count: 1

Call Stack:
[C]: ?
...ace\AddOns\NDui\Modules\ActionBar\Bars\Stancebar.lua:4: in main chunk

`AddOns\NDui\Modules\ActionBar\Bars\Petbar.lua:4:` attempt to index field 'bars' (a nil value)
Count: 1

Call Stack:
[C]: ?
AddOns\NDui\Modules\ActionBar\Bars\Petbar.lua:4: in main chunk

...AddOns\NDui\Modules\ActionBar\Bars\Leave_vehicle.lua:4: attempt to index field 'bars' (a nil value)
Count: 1

Call Stack:
[C]: ?
...AddOns\NDui\Modules\ActionBar\Bars\Leave_vehicle.lua:4: in main chunk

Any help would be apreciated...

So long 
Zabbel

**Comment by siweia** [comment]
You are not having a correct file replace. The error lines you listed are not even exists in 1.24.0.

**Comment by Zabbel** [comment]
Ok.. After deleting every single file folder everything is ok now.... Thank you for your help... :-)
