### ISSUE TITLE
NDui Classic - Raid Frame Lagging?

### ISSUE THREAD

**Issue by sscl500** [siweia/NDuiClassic#72]
Hello siweia,

I noticed that when playing this UI as a healer, it seems that the raid frame is lagging since the target's health suddenly gets filled up when there was no indication of incoming heal.

Ideally, it would be good if there is a way to optimise and reduce any lagging issue, but is this possible?
I saw one of the posting from one user here where he was testing the performance level of this UI.

Also, if we cannot solve the lagging issue, would there be an option where I could use other raid frame rather than the one built inside?

Thanks in advance!

**Comment by siweia** [comment]
Check options in your GUI pls.

**Comment by sscl500** [comment]
Could you please elaborate on your response as I am stuck on which gui options I need to check to ensure the best performance to reduce lagging issue?

**Comment by siweia** [comment]
See 'Frequent health update' under the 'RaidFrame' section.

**Comment by siweia** [comment]
Or simply disable raidframe and find some other addon that don't have the lagging issue you mentioned.
