### ISSUE TITLE
Command problem

### ISSUE THREAD

**Issue by DrMisadventure** [siweia/NDuiClassic#77]
Hi, in your FAQ there is this question and answer:

**Q: How to change opacity of UI? How to disable the font outlines?
A: /ac.**

/ac is not a valid command on ndui classic. 

I am looking for a way to disable the heavy font outline. I have unchecked Global Font Outline in Settings > Skins but the heavy outline will not go a way and the /ac command does not work.

Thank you.

**Comment by siweia** [comment]
Ignore the slash cmd.
The only options you can find are in the skins section in GUI, which is the one you mentioned, global font outline.
You need to reload ui to take any effects. And not all the fonts in the ui can be controlled by this option, there are still some font with outline that cannot be modified.
