### ISSUE TITLE
Quest Progress Notification sounds

### ISSUE THREAD

**Issue by sererinn** [siweia/NDuiClassic#79]
Hey, thanks for this addon, makes the whole world of a difference in Classic and Shadowlands!

On Classic, I was expecting the quest notification sound to do 2 sounds, one when quest is completed, another for QuestProgress, for example, Got to pick 8 things, 1 drops I loot, i was expecting a sound to notify on that. But I only get sounds when I have the full objectives completed. I have already disabled "Only play complete sound" but no good.

Is this a bug or working as intended?

**Comment by siweia** [comment]
It is intended.
'Only play complete sound' means that, stop sending progress messages, and only play the sound when you complete quests.
It never ever has a feature that play sound during progress.
