### ISSUE TITLE
Please report NDuiClassic for TBC beta here

### ISSUE THREAD

**Issue by NilkemoryaOryhara** [siweia/NDuiClassic#80]
Download the version for TBC beta at here:
https://github.com/siweia/NDuiClassic/tree/TBC

**Comment by siweia** [comment]
This shouldn't be an issue that NDuiClassic is currently for vanilla only, not for TBC yet.
Which of course, need lots of work to make changes. None of the errors you listed would be helpful atm.

**Comment by siweia** [comment]
I would only start to support TBC classic, once it goes on live.
Or join beta someday when I am available.

**Comment by siweia** [comment]
https://github.com/siweia/NDuiClassic/tree/TBC
