### ISSUE TITLE
NDuiClassic for TBC beta

### ISSUE THREAD

**Issue by siweia** [siweia/NDuiClassic#81]
You can download the version from this branch.
https://github.com/siweia/NDuiClassic/tree/TBC

Please post your issues here.

**Comment by NilkemoryaOryhara** [comment]
Seems to be somewhat working, however these errors are spammed at login. The main issue I immediately noticed on my Warrior was that all my action bars appear to be filled up correctly except for the main first bar that is meant to change with stances.

FrameXML\RestrictedExecution.lua:473: Cannot call restricted closure from insecure code
Count: 99

Call Stack:
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@FrameXML\RestrictedExecution.lua"]:473: in function <FrameXML\RestrictedExecution.lua:447>
[string "=(tail call)"]: ?
[string "@FrameXML\SecureHandlers.lua"]:499: in function <FrameXML\SecureHandlers.lua:473>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\SecureHandlers.lua"]:743: in function <FrameXML\SecureHandlers.lua:725>
[string "=(tail call)"]: ?
[string "@AddOns\NDui\Modules\ActionBar\Bars\Bar1.lua"]:133: in function `CreateBar1'
[string "@AddOns\NDui\Modules\ActionBar\Bars\Bar1.lua"]:157: in function `OnLogin'
[string "@AddOns\NDui\Init.lua"]:113: in function `func'
[string "@AddOns\NDui\Init.lua"]:23: in function <AddOns\NDui\Init.lua:18>

**Comment by siweia** [comment]
This need to be fixed by blizzard in future builds.
And make sure you have BaudErrorFrame enabled, which might stop the msg from popping out.

**Comment by NilkemoryaOryhara** [comment]
Yes, I copied that error message from BaudErrorFrame. Wasn't aware this was an issue on Blizzard's end, thank you.

**Comment by NilkemoryaOryhara** [comment]
Was working pretty well in the previous Beta patch. With the newest patch, seems to have some errors with settings fonts that breaks a lot of things like Unit Frames. Not sure if this is a mistake on Blizzard's end or something that AddOn developers need to update. Thank you for your work.

...ddOns\NDui\Modules\Skins\Blizzard\FrameXML\Fonts.lua:8: attempt to index local 'font' (a nil value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\NDui\Modules\Skins\Blizzard\FrameXML\Fonts.lua"]:8: in function `ReskinFont'
[string "@AddOns\NDui\Modules\Skins\Blizzard\FrameXML\Fonts.lua"]:90: in function `func'
[string "@AddOns\NDui\Modules\Skins\Skins.lua"]:18: in function `LoadDefaultSkins'
[string "@AddOns\NDui\Modules\Skins\Skins.lua"]:40: in function `OnLogin'
[string "@AddOns\NDui\Init.lua"]:113: in function `func'
[string "@AddOns\NDui\Init.lua"]:23: in function <AddOns\NDui\Init.lua:18>

**Comment by siweia** [comment]
If this is the only error in newest patch, 3dd438da9748ef95b844c4eeb826526744c90532 should do.

**Comment by NilkemoryaOryhara** [comment]
That seems to fix the issue with fonts.

There is an additional set of errors with the in-game Game Master help request button, which now looks much different from Classic (either a new or copy of Shadowlands version?). Renaming or removing HelpFrame.lua seems to allow the rest of the addon to work though.
![Untitled](https://user-images.githubusercontent.com/13921530/115326140-6ba07480-a152-11eb-9f57-4c72b9865303.png)

...s\NDui\Modules\Skins\Blizzard\FrameXML\HelpFrame.lua:9: attempt to index global 'HelpFrameHeader' (a nil value)
Count: 1

Call Stack:
[string "=[C]"]: ?
[string "@AddOns\NDui\Modules\Skins\Blizzard\FrameXML\HelpFrame.lua"]:9: in function `func'
[string "@AddOns\NDui\Modules\Skins\Skins.lua"]:18: in function `LoadDefaultSkins'
[string "@AddOns\NDui\Modules\Skins\Skins.lua"]:40: in function `OnLogin'
[string "@AddOns\NDui\Init.lua"]:113: in function `func'
[string "@AddOns\NDui\Init.lua"]:23: in function <AddOns\NDui\Init.lua:18>

**Comment by siweia** [comment]
Should all be fixed after 058caa673e0a6a56668fa62f603115ceb0cbb409.

**Comment by NilkemoryaOryhara** [comment]
Works well, no other issues noticed so far.
