### ISSUE TITLE
Sort bags broken by gemmed item

### ISSUE THREAD

**Issue by NilkemoryaOryhara** [siweia/NDuiClassic#83]
Sort bags appear to not work (just unresponsive when clicking the icon in bags or bank, no error) when you have an item with gems in it in your bags or bank.

This even occurs using NDui Classic 2.1.2 even with this recent bags fix (https://github.com/siweia/NDuiClassic/commit/b3cc7c023132d4c916f5b4ae06f736a438d04729)

**Comment by siweia** [comment]
I don't think so. Try to reinstall from github, it should work fine after that fix.

**Comment by NilkemoryaOryhara** [comment]
Definitely using 2.1.2 from GitHub, but still having the same issue. Not sure how else to explain it, it works fine until I put this item (https://tbc.wowhead.com/item=27527/greaves-of-the-shatterer) with these gems socketed into all 3 sockets (https://tbc.wowhead.com/item=28463/solid-zircon) into either my bags or bank. Then my bags or bank won't sort until I equip the item or move it somewhere else.

**Comment by siweia** [comment]
Should be good now.
I only tested item with one gem last night.

**Comment by NilkemoryaOryhara** [comment]
That works, thank you
