### ISSUE TITLE
[Skins] Vendor item sales with non-gold cost show an empty cost

### ISSUE THREAD

**Issue by NilkemoryaOryhara** [siweia/NDuiClassic#84]
In newer GitHub versions, this seems to be the case for anything that costs something like honor/BG marks, Spirit Shards, Holy Dust, etc.

![bug](https://user-images.githubusercontent.com/13921530/120895193-7f5c4900-c5e1-11eb-9477-d376e96bc34c.png)

**Comment by siweia** [comment]
bc38ad698de04ca1e3ef36918e3f8a1d7dea9d57 should have been fixed by this.

**Comment by NilkemoryaOryhara** [comment]
Not sure if it was a later fix, but seems to be working fine in 2.1.4
