### ISSUE TITLE
e is:open 奥数射击冷却没有计时条

### ISSUE THREAD

**Issue by kevin7518** [siweia/NDuiClassic#87]
LR加了奥术射击天赋后，没有冷却计时条 2.2.7  2.2.9 都不行

**Comment by siweia** [comment]
不知道你在说什么

**Comment by kevin7518** [comment]
控制台 - 技能监控- 冷却计时-添加 奥术射击，不加LR强化奥术射击天赋，可以监控计时冷却，加了天赋以后就不监控了冷却了

**Comment by siweia** [comment]
那说明法术ID变了啊，重新加一个强化后的id不就好了

**Comment by siweia** [comment]
那说明法术ID变了啊，重新加一个强化后的id不就好了
