### ISSUE TITLE
牧师暗抗 暗影防护祷言 与默认 防护暗影药水 监控冲突

### ISSUE THREAD

**Issue by yeasiz** [siweia/NDuiClassic#92]
牧师的暗抗buff，暗影防护祷言 Spell = 27683 与内置的 防护暗影药水 AuraID = 28537 冲突，期望该 buff 应只在右上角显示。

目前团队牧师上了暗抗 buff 后会一直在附魔及饰品监控中出现，注释插件默认的 防护暗影药水 后正常。

NDui\Config\AuraWatchList\All.lua

--{AuraID = 28537, UnitID = "player"},	-- 防护暗影药水

**Comment by siweia** [comment]
关闭技能监控里的，监控法术的不同等级
