### ISSUE TITLE
Lua error on action bar CD call.

### ISSUE THREAD

**Issue by ProfessorMc** [siweia/NDuiClassic#94]
Message: Interface\AddOns\NDui\Modules\ActionBar\Cooldown.lua:117: attempt to index a nil value
Time: Mon Dec  6 13:15:14 2021
Count: 11
Stack: Interface\AddOns\NDui\Modules\ActionBar\Cooldown.lua:117: attempt to index a nil value

Conflict with another Addon that is using bar CD's.  Added a null check to this line and it fixed it.  Submitting pr shortly.

**Comment by siweia** [comment]
Thx.
