### ISSUE TITLE
Saving UI Frame Location

### ISSUE THREAD

**Issue by Systern** [siweia/NDuiClassic#96]
Hey Siweia - really appreciate your addon. NDui is my go-to way to play classic.

I do have a request for a hopefully small change. My character frame, quest log, spellbook, and social ui element are anchored where I'd like my raid frames. Unfortunately, I can't seem to move the anchor for these frames within NDui nor can I do it via the MoveAnything addon (presumably because they're modified by NDui in some way).

Any chance this could be a feature enhancement soon? No worries if not though... I'll still use NDui because it's so great! :)

**Comment by Systern** [comment]
Also adding a picture in the case my description isn't clear. 

[](https://imgur.com/a/vX3V1iF)

**Comment by Systern** [comment]
https://imgur.com/a/vX3V1iF

**Comment by siweia** [comment]
The default ui frames' anchor all reset by blizz UIParent manager. There are no way to store the anchors with taint issues.

**Comment by Systern** [comment]
> The default ui frames' anchor all reset by blizz UIParent manager. There are no way to store the anchors without taint issues.

Thank you for the reply. Closing the issue :)
